apiVersion: apps/v1
kind: Deployment
metadata:
  name: goviolin-deployment
spec:
  selector:
    matchLabels:
      app: goviolin
  replicas: 1
  template:
    metadata: 
      labels:
        app: goviolin
    spec:
      containers:
      - name: goviolin
        image: yehias21/goviolin
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: goviolin-service
spec:
  selector:
    app: goviolin
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8080
      nodePort: 32000
  type: LoadBalancer
